from __future__ import annotations

from autopilot.models import AuthMode, Capability, ConnectorCatalogItem


CATALOG: list[ConnectorCatalogItem] = [
    ConnectorCatalogItem(
        id="gmail",
        name="Gmail",
        category="Communication",
        description="Search inbox threads, summarize escalations, and draft replies.",
        icon="GM",
        auth_mode=AuthMode.OAUTH,
        capabilities=[Capability.READ, Capability.SEARCH, Capability.WRITE],
        event_types=["email.received", "thread.updated"],
        scopes=["gmail.read", "gmail.compose"],
        safe_actions=["draft_email"],
        objects=["emails", "threads", "attachments"],
    ),
    ConnectorCatalogItem(
        id="slack",
        name="Slack",
        category="Communication",
        description="Search channels, post operational updates, and listen for escalations.",
        icon="SL",
        auth_mode=AuthMode.WEBHOOK,
        capabilities=[Capability.READ, Capability.SEARCH, Capability.NOTIFY, Capability.ACTION],
        event_types=["message.posted", "mention.created"],
        scopes=["channels.read", "chat.write"],
        safe_actions=["post_message", "notify_ops"],
        implemented_actions=["notify_ops"],
        objects=["channels", "messages", "users"],
        implemented=True,
    ),
    ConnectorCatalogItem(
        id="google_drive",
        name="Google Drive",
        category="Knowledge",
        description="Search shared docs, read runbooks, and attach evidence to missions.",
        icon="GD",
        auth_mode=AuthMode.OAUTH,
        capabilities=[Capability.READ, Capability.SEARCH],
        scopes=["drive.readonly"],
        objects=["documents", "folders", "files"],
    ),
    ConnectorCatalogItem(
        id="notion",
        name="Notion",
        category="Knowledge",
        description="Read team knowledge bases and publish structured mission briefs.",
        icon="NO",
        auth_mode=AuthMode.API_KEY,
        capabilities=[Capability.READ, Capability.SEARCH, Capability.WRITE],
        scopes=["pages.read", "pages.write"],
        safe_actions=["create_page"],
        objects=["pages", "databases"],
    ),
    ConnectorCatalogItem(
        id="linear",
        name="Linear",
        category="Engineering",
        description="Read issues, create follow-up tasks, and update incident workflows.",
        icon="LN",
        auth_mode=AuthMode.API_KEY,
        capabilities=[Capability.READ, Capability.SEARCH, Capability.WRITE, Capability.ACTION],
        event_types=["issue.created", "issue.updated"],
        scopes=["issues.read", "issues.write"],
        safe_actions=["create_issue", "comment_issue"],
        implemented_actions=["create_issue"],
        objects=["issues", "teams", "projects"],
        implemented=True,
    ),
    ConnectorCatalogItem(
        id="jira",
        name="Jira",
        category="Engineering",
        description="Search tickets, correlate incidents, and create remediation tasks.",
        icon="JI",
        auth_mode=AuthMode.OAUTH,
        capabilities=[Capability.READ, Capability.SEARCH, Capability.WRITE, Capability.ACTION],
        event_types=["issue.created", "issue.updated"],
        scopes=["issues.read", "issues.write"],
        safe_actions=["create_ticket", "comment_ticket"],
        objects=["issues", "projects", "boards"],
    ),
    ConnectorCatalogItem(
        id="sentry",
        name="Sentry",
        category="Observability",
        description="Ingest error alerts, inspect stack traces, and correlate regressions.",
        icon="SE",
        auth_mode=AuthMode.WEBHOOK,
        capabilities=[Capability.READ, Capability.SEARCH, Capability.ACTION],
        event_types=["error.created", "issue.regression"],
        scopes=["events.read", "issues.read"],
        safe_actions=["mark_investigating"],
        objects=["errors", "releases", "stack traces"],
        implemented=True,
    ),
    ConnectorCatalogItem(
        id="pagerduty",
        name="PagerDuty",
        category="Observability",
        description="Receive incidents, inspect escalation context, and post updates.",
        icon="PD",
        auth_mode=AuthMode.WEBHOOK,
        capabilities=[Capability.READ, Capability.ACTION, Capability.NOTIFY],
        event_types=["incident.triggered", "incident.resolved"],
        scopes=["incidents.read", "incidents.write"],
        safe_actions=["add_note", "notify_oncall"],
        objects=["incidents", "services", "escalation policies"],
    ),
    ConnectorCatalogItem(
        id="zendesk",
        name="Zendesk",
        category="Support",
        description="Read support tickets, detect escalations, and draft customer-safe updates.",
        icon="ZD",
        auth_mode=AuthMode.API_KEY,
        capabilities=[Capability.READ, Capability.SEARCH, Capability.WRITE],
        event_types=["ticket.created", "ticket.updated"],
        scopes=["tickets.read", "tickets.write"],
        safe_actions=["draft_reply", "tag_ticket"],
        objects=["tickets", "customers", "organizations"],
    ),
    ConnectorCatalogItem(
        id="web_search",
        name="Web Search",
        category="Research",
        description="Search public web sources for live context and external validation.",
        icon="WS",
        auth_mode=AuthMode.API_KEY,
        capabilities=[Capability.SEARCH, Capability.READ],
        scopes=["web.search"],
        objects=["web results", "pages"],
        implemented=True,
    ),
    ConnectorCatalogItem(
        id="local_artifacts",
        name="Local Artifacts",
        category="System",
        description="Write durable reports, action packets, and local audit records.",
        icon="AR",
        auth_mode=AuthMode.NONE,
        capabilities=[Capability.WRITE, Capability.ACTION],
        scopes=["files.write"],
        safe_actions=["write_report", "write_action_packet"],
        implemented_actions=["write_report", "write_action_packet"],
        objects=["reports", "audit files"],
        implemented=True,
    ),
]


def catalog_by_id() -> dict[str, ConnectorCatalogItem]:
    return {item.id: item for item in CATALOG}
