from __future__ import annotations

from typing import Protocol, runtime_checkable, Any

from autopilot.models import Mission, OperatorStep, Signal, AgentTask, ActionRecord


@runtime_checkable
class StoreInterface(Protocol):
    def save_signal(self, signal: Signal, mission_id: str | None = None) -> None: ...

    def create_mission(self, mission: Mission) -> None: ...

    def update_mission(self, mission: Mission) -> None: ...

    def get_mission(self, mission_id: str) -> Mission | None: ...

    def list_missions(self, limit: int = 50) -> list[dict[str, Any]]: ...

    def active_missions(self) -> list[Mission]: ...

    def add_step(self, step: OperatorStep) -> None: ...

    def list_steps(self, mission_id: str) -> list[dict[str, Any]]: ...

    def trace(
        self,
        mission_id: str | None,
        name: str,
        status: str,
        payload: dict[str, Any],
        parent_step_id: str | None = None,
    ) -> None: ...

    def list_traces(
        self, mission_id: str | None = None, limit: int = 100
    ) -> list[dict[str, Any]]: ...

    def remember(self, key: str, value: str) -> None: ...

    def recall(self, key_like: str, limit: int = 5) -> list[str]: ...

    def save_agent_task(self, task: AgentTask) -> None: ...

    def get_agent_tasks(self, mission_id: str) -> list[AgentTask]: ...

    def save_action_record(self, record: ActionRecord) -> None: ...

    def get_action_records(self, mission_id: str) -> list[ActionRecord]: ...
